import { describe, expect, it, vi } from 'vitest';
import { State } from '../src/core/state';
import { GeneralSearchConversationService } from '../src/core/general-search-conversation';
import { defaultSettings } from '../src/settings';
import type { Release } from '../src/types/prowlarr';

const release=(overrides:Partial<Release>={}):Release=>({guid:'guid-safe',age:4,size:123,files:null,grabs:null,indexerId:4,indexer:'Indexer',subGroup:null,title:'Example film',tvdbId:null,tmdbId:null,publishDate:'',downloadUrl:'https://private.test/key',indexerFlags:[],categories:[],magnetUrl:'magnet:?xt=x',infoHash:'hash',seeders:2,leechers:1,protocol:'torrent',downloadClientId:null,...overrides});
const searchPlan=(...queries:string[])=>({mode:'search',question:'',searchSpace:{focus:'category',identityAnchors:[],medium:{value:null,provenance:'unknown'},positives:[],negatives:[],expansionScope:'subcategories'},proposals:queries.map((query)=>({query,purpose:'Search this topic',branch:'topic',strategy:'subcategory',preserves:[]}))});
const clarifyPlan=(question:string)=>({mode:'clarify',question,searchSpace:{focus:'mixed',identityAnchors:[],medium:{value:null,provenance:'unknown'},positives:[],negatives:[],expansionScope:'identity-preserving'},proposals:[]});
function fixture(results=[release()]) {const state=State.open(':memory:');const settings=structuredClone(defaultSettings);settings.integrations.prowlarr={url:'http://prowlarr.test',apiKey:'p-secret',tvClient:'',movieClient:'',generalClient:'General'};settings.ai.apiKey='a-secret';const destination={id:1,name:'General',enable:true,protocol:'torrent' as const,supportsCategories:true,categories:[],routingDigest:'a'.repeat(64)};const llm={json:vi.fn(async(args:{label:string;user:string})=>args.label.includes('planning')?searchPlan('film term','film term'):{items:(JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>}).actualResults.map(x=>({releaseId:x.releaseId,classification:'match'}))})};const prowlarr={getDownloadClients:vi.fn(async()=>[destination]),search:vi.fn(async()=>results)};const rebuild=()=>new GeneralSearchConversationService({llm:llm as never,prowlarr:prowlarr as never,state,getSettings:()=>settings});return {state,settings,llm,prowlarr,rebuild,service:rebuild()};}
const request={originalQuery:'find a film',turns:[{role:'user',content:'find a film'}] as const,action:'search' as const};

describe('GeneralSearchConversationService',()=>{
  it('appends authored search instructions to planner and curator system messages only',async()=>{const f=fixture();f.settings.ai.searchSystemPrompt='Keep it broad.\n Preserve this line.';f.service=f.rebuild();await f.service.search(request);const systems=f.llm.json.mock.calls.map(([args])=>(args as unknown as {system:string}).system);expect(systems.length).toBeGreaterThanOrEqual(2);expect(systems.every(x=>x.includes('User-configured system instructions:\nKeep it broad.\n Preserve this line.'))).toBe(true);});
  it('returns a safe typed provider refusal before any Prowlarr access and does not repair or fall back',async()=>{const f=fixture();f.llm.json.mockRejectedValueOnce(Object.assign(new Error('provider-refusal'),{code:'provider-refusal'}));await expect(f.service.search(request)).rejects.toMatchObject({code:'provider-refusal'});expect(f.prowlarr.getDownloadClients).not.toHaveBeenCalled();expect(f.prowlarr.search).not.toHaveBeenCalled();expect(f.llm.json).toHaveBeenCalledTimes(1);});
  it('routes structured diverse branches as the existing string-query contract',async()=>{const f=fixture();f.settings.generalSearch={maxQueries:2,maxCandidates:20,maxAiCalls:10,batchSize:20,displayLimit:20,hideZeroSeeders:true};f.service=f.rebuild();const space={focus:'category',identityAnchors:[],medium:{value:'videogame',provenance:'explicit'},positives:[],negatives:[{text:'match recordings',strength:'hard'}],expansionScope:'subcategories'};const make=(...queries:string[])=>({mode:'search',question:'',searchSpace:space,proposals:queries.map(query=>({query,purpose:'Cover a sport subcategory',branch:query.split(' ')[0],strategy:'subcategory',preserves:[]}))});let plans=0;f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning'))return plans++===0?make('basketball videogames','soccer videogames'):make('soccer videogames');const input=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};return {items:input.actualResults.map(item=>({releaseId:item.releaseId,classification:'match'}))};}) as never;const searchQueries:string[]=[];f.prowlarr.search=vi.fn(async({query}:{query:string})=>{searchQueries.push(query);return [release({guid:query,title:query})];}) as never;const result=await f.service.search({...request,budgets:{queryCount:2,aiCalls:10}});expect(searchQueries).toEqual(['basketball videogames','soccer videogames']);expect(result.queries).toEqual(['basketball videogames','soccer videogames']);});
  it('freezes interpreted medium, exclusions, restrictions, and fingerprint across adaptation',async()=>{
    const f=fixture();f.settings.generalSearch={maxQueries:2,maxCandidates:20,maxAiCalls:8,batchSize:20,displayLimit:20,hideZeroSeeders:true};f.service=f.rebuild();
    const original={...searchPlan('Film title first','Film title Different show second').searchSpace,focus:'mixed',identityAnchors:['Film title'],medium:{value:'film',provenance:'explicit'},positives:[{text:'documentary',strength:'hard'}],negatives:[{text:'exclude sequels',strength:'hard'}],expansionScope:'identity-preserving'};
    const mutated={...original,medium:{value:'television series',provenance:'explicit'},positives:[{text:'sports',strength:'hard'}],negatives:[],identityAnchors:['Different show'],expansionScope:'associations'};
    let planning=0;const curationInputs:Record<string,unknown>[]=[];
    f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning'))return planning++===0?{...searchPlan('Film title first'),proposals:[{...searchPlan('Film title first').proposals[0]!,preserves:['Film title']}],searchSpace:original}:{...searchPlan('Film title Different show second'),proposals:[{...searchPlan('Film title Different show second').proposals[0]!,preserves:['Different show','Film title']}],searchSpace:mutated};const input=JSON.parse(args.user) as Record<string,unknown>;curationInputs.push(input);const ids=(input.actualResults as Array<{releaseId:string}>).map(x=>x.releaseId);return {items:ids.map(releaseId=>({releaseId,classification:'match'}))};}) as never;
    f.prowlarr.search=vi.fn(async({query}:{query:string})=>[release({guid:query,title:query})]) as never;
    const result=await f.service.search({...request,budgets:{queryCount:2,aiCalls:8}});
    expect(curationInputs).toHaveLength(2);for(const input of curationInputs){expect(input.constraints).toEqual(original);expect(input.constraintVersion).toBe(curationInputs[0]!.constraintVersion);}
    expect(planning).toBe(2);expect(result.queries).toEqual(['Film title first','Film title Different show second']);expect(result.releases).toHaveLength(2);
  });
  it('rejects an adaptation whose proposal no longer satisfies frozen identity criteria but preserves prior verified partials',async()=>{
    const f=fixture([release({guid:'frozen-partial',title:'Previously verified'})]);f.settings.generalSearch={maxQueries:2,maxCandidates:10,maxAiCalls:8,batchSize:10,displayLimit:10,hideZeroSeeders:true};f.service=f.rebuild();let planning=0,curation=0;
    const initialSpace={...searchPlan('Original Title film').searchSpace,focus:'unique-title',identityAnchors:['Original Title'],medium:{value:'film',provenance:'explicit'}};
    const mutatedSpace={...initialSpace,identityAnchors:['Different Series'],medium:{value:'television series',provenance:'explicit'},negatives:[]};
    f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning')){planning++;const query=planning===1?'Original Title film':'Different Series television';const plan=searchPlan(query);return {...plan,searchSpace:planning===1?initialSpace:mutatedSpace,proposals:[{...plan.proposals[0]!,preserves:[planning===1?'Original Title':'Different Series']}]};}curation++;const d=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};return {items:d.actualResults.map(x=>({releaseId:x.releaseId,classification:'match'}))};}) as never;
    const events:unknown[]=[],save=vi.spyOn(f.state,'saveGeneralSearchSnapshot');await expect(f.service.search({...request,budgets:{queryCount:2,aiCalls:8}},e=>events.push(e))).rejects.toMatchObject({code:'invalid-search-plan'});
    expect(planning).toBe(2);expect(curation).toBe(1);expect(f.prowlarr.search).toHaveBeenCalledTimes(1);expect(save).not.toHaveBeenCalled();expect(events.at(-1)).toMatchObject({type:'error',partialReleases:[{title:'Previously verified',selectable:false}]});
  });
  it('keeps find-more on prior authenticated intent instead of accepting a contradictory reinterpretation',async()=>{
    const f=fixture([release({guid:'find-more-authenticated',title:'Original Title candidate'})]);f.settings.generalSearch={maxQueries:2,maxCandidates:10,maxAiCalls:8,batchSize:10,displayLimit:10,hideZeroSeeders:true};f.service=f.rebuild();
    const originalSpace={...searchPlan('Original Title film').searchSpace,focus:'unique-title',identityAnchors:['Original Title'],medium:{value:'film',provenance:'explicit'},negatives:[{text:'not television',strength:'hard'}]};
    f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning'))return {...searchPlan('Original Title film'),searchSpace:originalSpace,proposals:[{...searchPlan('Original Title film').proposals[0]!,preserves:['Original Title']}]};const d=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};return {items:d.actualResults.map(x=>({releaseId:x.releaseId,classification:'match'}))};}) as never;
    const first=await f.service.search({...request,budgets:{queryCount:1,aiCalls:8}}),previous=first.releases[0]!;
    f.llm.json=vi.fn(async(args:{label:string})=>args.label.includes('planning')?{...searchPlan('Different Series television'),searchSpace:{...originalSpace,identityAnchors:['Different Series'],medium:{value:'television series',provenance:'explicit'},negatives:[]},proposals:[{...searchPlan('Different Series television').proposals[0]!,preserves:['Different Series']}]}:{items:[]}) as never;
    const events:unknown[]=[],save=vi.spyOn(f.state,'saveGeneralSearchSnapshot');await expect(f.service.search({...request,action:'find-more',previousSearchId:first.searchId!,confirmationToken:first.confirmationToken!,budgets:{queryCount:2,aiCalls:8}},e=>events.push(e))).rejects.toMatchObject({code:'invalid-search-plan'});
    expect(f.prowlarr.search).toHaveBeenCalledTimes(1);expect(save).not.toHaveBeenCalled();expect(events.at(-1)).toMatchObject({type:'error',partialReleases:[{releaseId:previous.releaseId,selectable:false}]});
  });
  it('treats newly added find-more user requirements as a genuine refinement and reassesses before admission',async()=>{
    const f=fixture([release({guid:'new-requirement-result',title:'Not a sequel'})]);f.settings.generalSearch={maxQueries:1,maxCandidates:10,maxAiCalls:10,batchSize:10,displayLimit:10,hideZeroSeeders:true};f.service=f.rebuild();let planning=0,curation=0;
    const base={...searchPlan('initial film search').searchSpace,focus:'mixed',identityAnchors:[],medium:{value:'film',provenance:'explicit'},positives:[],negatives:[],expansionScope:'identity-preserving'};
    f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning')){planning++;return {...searchPlan(planning===1?'initial film search':'updated film search'),searchSpace:planning===1?base:{...base,negatives:[{text:'exclude sequels',strength:'hard'}]}};}curation++;const d=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>;constraints:{negatives:Array<{text:string}>}};if(curation===2)expect(d.constraints.negatives).toEqual([{text:'exclude sequels',strength:'hard'}]);return {items:d.actualResults.map(x=>({releaseId:x.releaseId,classification:curation===1?'match':'clearly-unrelated'}))};}) as never;
    const first=await f.service.search({...request,budgets:{queryCount:1,aiCalls:10}}),oldExpiry=first.releases[0]!.expiresAt;
    f.prowlarr.search=vi.fn(async()=>[]) as never;const turns=[{role:'user',content:'find a film'},{role:'assistant',content:'Any exclusions?'},{role:'user',content:'exclude sequels'}] as const;
    const refined=await f.service.search({...request,turns,action:'find-more',previousSearchId:first.searchId!,confirmationToken:first.confirmationToken!,budgets:{queryCount:1,aiCalls:10}});
    const payload=f.state.getGeneralSearchSnapshot(refined.searchId!)!.payload as {releases:Array<unknown>;candidateLedger:Array<{public:{assessment:{status:string;constraintVersion:string};expiresAt:string}}>};
    expect(refined.releases).toEqual([]);expect(refined.diagnostics?.ledger.reassessed).toBe(1);expect(payload.releases).toEqual([]);expect(payload.candidateLedger[0]?.public.assessment).toMatchObject({status:'rejected'});expect(payload.candidateLedger[0]?.public.assessment.constraintVersion).not.toBe((f.state.getGeneralSearchSnapshot(first.searchId!)!.payload as {constraintVersion:string}).constraintVersion);expect(payload.candidateLedger[0]?.public.expiresAt).toBe(oldExpiry);
  });
  it('asks a material medium/episode clarification without an indexer query',async()=>{const f=fixture();const clarify={mode:'clarify',question:'Which season do you mean?',searchSpace:{focus:'mixed',identityAnchors:['Example Series','episode 4'],medium:{value:'television series',provenance:'context'},positives:[],negatives:[],expansionScope:'identity-preserving'},proposals:[]};f.llm.json.mockResolvedValueOnce(clarify as never);const result=await f.service.search({...request,originalQuery:'Example Series episode 4',turns:[{role:'user',content:'Example Series episode 4'}]});expect(result.status).toBe('clarification-needed');expect(result.question).toBe('Which season do you mean?');expect(f.prowlarr.search).not.toHaveBeenCalled();});
  it('repairs one malformed planner output within the actual AI-call budget, then fails closed',async()=>{const f=fixture();f.settings.generalSearch={maxQueries:1,maxCandidates:20,maxAiCalls:2,batchSize:20,displayLimit:20,hideZeroSeeders:true};f.service=f.rebuild();f.prowlarr.search=vi.fn(async()=>[]);f.llm.json.mockReset();f.llm.json.mockResolvedValueOnce({mode:'search',proposals:[{query:'bad\nprose'}]} as never).mockResolvedValueOnce(searchPlan('fixed term') as never);const result=await f.service.search({...request,budgets:{queryCount:1,aiCalls:2}});expect(result.queries).toEqual([]);expect(f.llm.json).toHaveBeenCalledTimes(2);expect(f.prowlarr.search).not.toHaveBeenCalled();const failed=fixture();failed.settings.generalSearch={maxQueries:1,maxCandidates:20,maxAiCalls:2,batchSize:20,displayLimit:20,hideZeroSeeders:true};failed.service=failed.rebuild();failed.llm.json.mockReset();failed.llm.json.mockResolvedValue({mode:'search',proposals:[{query:'bad\nprose'}]} as never);await expect(failed.service.search({...request,budgets:{queryCount:1,aiCalls:2}})).rejects.toMatchObject({code:'invalid-search-plan'});expect(failed.prowlarr.search).not.toHaveBeenCalled();expect(failed.llm.json).toHaveBeenCalledTimes(2);});
  it('repairs follow-ups with the full sanitized planning context and never echoes rejected output',async()=>{const f=fixture([release({guid:'seed',title:'Seed candidate'})]);f.settings.generalSearch={maxQueries:1,maxCandidates:20,maxAiCalls:12,batchSize:20,displayLimit:20,hideZeroSeeders:true};f.service=f.rebuild();const initial=await f.service.search({...request,budgets:{queryCount:1,aiCalls:12}});const bad={...searchPlan('https://private.invalid/path?token=private-secret'),searchSpace:{...searchPlan('unused').searchSpace,focus:'mixed',identityAnchors:['Example film'],medium:{value:'film',provenance:'context'},negatives:[{text:'exclude sequels',strength:'hard'}]}};let plannerCalls=0;f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning'))return plannerCalls++===0?bad:searchPlan('fresh topic');const input=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};return {items:input.actualResults.map(x=>({releaseId:x.releaseId,classification:'match'}))};}) as never;const events:unknown[]=[];const turns=[{role:'user',content:'find a film'},{role:'assistant',content:'Which style?'},{role:'user',content:'prefer documentaries'}] as const;const result=await f.service.search({...request,turns,action:'find-more',previousSearchId:initial.searchId!,confirmationToken:initial.confirmationToken!,selectedInspirationIds:[initial.releases[0]!.releaseId],budgets:{queryCount:1,aiCalls:12}},event=>events.push(event));const repair=JSON.parse(f.llm.json.mock.calls[1]![0].user) as Record<string,any>;expect(repair).toMatchObject({original:'find a film',action:'find-more',turns,executedQueries:['film term'],budget:1,correction:{failureCodes:['invalid-search-plan']}});expect(repair.previousResults[0].title).toBe('Seed candidate');expect(repair.inspiration.inspiration).toEqual([{title:'Seed candidate',protocol:'torrent'}]);expect(repair).not.toHaveProperty('invalidOutput');const serialized=JSON.stringify({calls:f.llm.json.mock.calls,events,snapshot:f.state.getGeneralSearchSnapshot(result.searchId!)?.payload,result});expect(serialized).not.toContain('private.invalid');expect(serialized).not.toContain('private-secret');});
  it('keeps cancellation and settings drift authoritative during planner repair',async()=>{for(const change of ['abort','settings'] as const){const f=fixture();let repairStarted!:()=>void,release!:()=>void;const started=new Promise<void>(resolve=>{repairStarted=resolve;}),gate=new Promise<void>(resolve=>{release=resolve;});let planning=0;f.llm.json=vi.fn(async(args:{label:string})=>{if(args.label.includes('planning')){planning++;if(planning===1)return searchPlan('bad\noutput');repairStarted();await gate;if(change==='settings')f.settings.ai.model='rotated-after-repair';return searchPlan('repaired');}return {items:[]};}) as never;const controller=new AbortController();const pending=f.service.search(request,undefined,controller.signal);await started;if(change==='abort')controller.abort();else f.settings.ai.model='rotated-before-repair';release();await expect(pending).rejects.toMatchObject({code:change==='abort'?'aborted':'settings-changed'});expect(f.llm.json).toHaveBeenCalledTimes(2);expect(f.prowlarr.search).not.toHaveBeenCalled();}});
  it('searches bounded unique terms and emits truthful ordered progress',async()=>{const f=fixture();const events:string[]=[];const result=await f.service.search(request,e=>events.push(e.type));expect(f.prowlarr.search).toHaveBeenCalledTimes(1);expect(result.releases).toHaveLength(1);expect(events[0]).toBe('planning');expect(events.at(-1)).toBe('complete');expect(events).toContain('results');});
  it('feeds the retrieval ledger to adaptive planning and reports raw, duplicate, filter, and zero-novelty outcomes',async()=>{const f=fixture();f.settings.generalSearch={maxQueries:2,maxCandidates:20,maxAiCalls:8,batchSize:20,displayLimit:20,hideZeroSeeders:true};f.service=f.rebuild();const first=release({guid:'same-guid',title:'Candidate'}),queried:string[]=[];f.prowlarr.search=vi.fn(async({query}:{query:string})=>{queried.push(query);return query==='first'? [first,release({guid:'zero-guid',seeders:0}),release({guid:'unsupported',protocol:'unknown'})]:[first];}) as never;f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning'))return searchPlan('first','second');const data=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};return {items:data.actualResults.map(x=>({releaseId:x.releaseId,classification:'match'}))};}) as never;const result=await f.service.search({...request,budgets:{queryCount:2,aiCalls:8}},undefined);const ledger=result.diagnostics!.ledger;expect(queried).toEqual(['first','second']);expect(ledger).toMatchObject({raw:4,added:2,duplicates:1,filtered:{'availability-zero-seeders':1,'unsupported-protocol':1},assessed:{match:1,possible:0,unrelated:0,unassessed:1}});expect(result.diagnostics).toMatchObject({complete:true,stopReason:'no-novelty'});expect(result.queries).toEqual(['first','second']);});
  it('continues to a useful queued branch after an empty or deterministically filtered first query',async()=>{
    for(const firstResult of [[],[release({guid:'filtered-first',protocol:'unknown'})]]){
      const f=fixture();f.settings.generalSearch={maxQueries:3,maxCandidates:10,maxAiCalls:8,batchSize:10,displayLimit:10,hideZeroSeeders:true};f.service=f.rebuild();let planning=0;
      f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning'))return planning++===0?searchPlan('first branch'):searchPlan('second branch');const d=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};return {items:d.actualResults.map(x=>({releaseId:x.releaseId,classification:'match'}))};}) as never;
      f.prowlarr.search=vi.fn(async({query}:{query:string})=>query==='first branch'?firstResult:[release({guid:`success-${firstResult.length}`,title:'Valid result'})]) as never;
      const result=await f.service.search({...request,budgets:{queryCount:3,aiCalls:8}});expect(result.queries).toContain('second branch');expect(result.releases.some(x=>x.title==='Valid result')).toBe(true);
    }
  });
  it('bounds duplicate-only retrieval rounds without miscounting duplicates as admissions',async()=>{
    const f=fixture();f.settings.generalSearch={maxQueries:5,maxCandidates:20,maxAiCalls:8,batchSize:10,displayLimit:10,hideZeroSeeders:true};f.service=f.rebuild();f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning'))return searchPlan('first','duplicate-a','duplicate-b','duplicate-c','duplicate-d');const d=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};return {items:d.actualResults.map(x=>({releaseId:x.releaseId,classification:'match'}))};}) as never;
    f.prowlarr.search=vi.fn(async()=>[release({guid:'same-identity'})]) as never;const result=await f.service.search({...request,budgets:{queryCount:5,aiCalls:8}});
    expect(f.prowlarr.search).toHaveBeenCalledTimes(3);expect(result.diagnostics?.stopReason).toBe('low-yield');expect(result.diagnostics?.ledger).toMatchObject({added:1,duplicates:2,reactivated:0});
  });
  it('deduplicates repeated identities within one source response before curation',async()=>{
    const f=fixture();const duplicate=release({guid:'same-response-id'});f.prowlarr.search=vi.fn(async()=>[duplicate,{...duplicate,title:'Changed duplicate title'}]) as never;
    const curationIDs:string[][]=[];f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning'))return searchPlan('duplicate batch');const d=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};curationIDs.push(d.actualResults.map(x=>x.releaseId));return {items:d.actualResults.map(x=>({releaseId:x.releaseId,classification:'match'}))};}) as never;
    const result=await f.service.search({...request,budgets:{queryCount:1,aiCalls:3}});expect(curationIDs).toHaveLength(1);expect(curationIDs[0]).toHaveLength(1);expect(result.releases).toHaveLength(1);expect(result.diagnostics?.ledger).toMatchObject({raw:2,added:1,duplicates:1,reactivated:0});
  });
  it('rejects credential-bearing references from every prompt, event, snapshot, and response',async()=>{
    const refs=['https://secret.example/api?token=abc','alice:hunter2@private-host','magnet:?xt=urn:btih:privatehash','p-secret'];
    const f=fixture(refs.map((guid,i)=>release({guid:`${i}-${guid}`,downloadUrl:`${i}-${guid}`})));
    const events:unknown[]=[];const result=await f.service.search(request,e=>events.push(e));
    const snapshot=f.state.getGeneralSearchSnapshot(result.searchId!)!;
    const data=JSON.stringify({prompts:f.llm.json.mock.calls,events,snapshot:snapshot.payload,response:result});
    expect(result.releases).toHaveLength(0);for(const raw of refs)expect(data).not.toContain(raw);
    expect(data).not.toContain('hunter2');expect(data).not.toContain('privatehash');expect(data).not.toContain('secret.example');
  });
  it('rejects private references in interpreted search-space fields before retrieval or persistence',async()=>{
    const f=fixture();
    const plan={...searchPlan('safe term'),searchSpace:{...searchPlan('safe term').searchSpace,identityAnchors:['private-anchor-secret'],medium:{value:'medium-secret',provenance:'explicit'},positives:[{text:'positive-secret',strength:'hard'}],negatives:[{text:'negative-secret',strength:'hard'}]}};
    f.llm.json=vi.fn(async(args:{label:string})=>args.label.includes('planning')?plan:({items:[]})) as never;
    const events:unknown[]=[],save=vi.spyOn(f.state,'saveGeneralSearchSnapshot');
    await expect(f.service.search(request,e=>events.push(e))).rejects.toMatchObject({code:'invalid-search-plan'});
    expect(f.prowlarr.search).not.toHaveBeenCalled();expect(save).not.toHaveBeenCalled();
    const observed=JSON.stringify({prompts:f.llm.json.mock.calls,events});
    for(const secret of ['private-anchor-secret','medium-secret','positive-secret','negative-secret'])expect(observed).not.toContain(secret);
  });
  it.each(['medium','identity-anchor','positive','negative'] as const)('rejects configured credentials in the %s search-space field without retaining or echoing them',async(field)=>{
    const f=fixture();const base=searchPlan('safe term').searchSpace;
    const space=field==='medium'?{...base,medium:{value:'p-secret',provenance:'explicit'}}:field==='identity-anchor'?{...base,identityAnchors:['p-secret']}:field==='positive'?{...base,positives:[{text:'p-secret',strength:'hard'}]}:{...base,negatives:[{text:'p-secret',strength:'hard'}]};
    f.llm.json=vi.fn(async(args:{label:string})=>args.label.includes('planning')?{...searchPlan('safe term'),searchSpace:space}:({items:[]})) as never;
    const events:unknown[]=[],save=vi.spyOn(f.state,'saveGeneralSearchSnapshot');await expect(f.service.search(request,e=>events.push(e))).rejects.toMatchObject({code:'invalid-search-plan'});
    const boundary=JSON.stringify({prompts:f.llm.json.mock.calls,events});expect(boundary).not.toContain('p-secret');expect(save).not.toHaveBeenCalled();expect(f.prowlarr.search).not.toHaveBeenCalled();
  });
  it('hides zero-seeder torrents while preserving unknown, stale, and protocol-specific signals',async()=>{const f=fixture([release({guid:'zero',title:'Zero',seeders:0}),release({guid:'unknown-seeds',title:'Unknown seeds',seeders:null}),release({guid:'stale',title:'Stale',age:500}),release({guid:'usenet',title:'Usenet',protocol:'usenet',seeders:0})]);const result=await f.service.search(request);expect(result.releases.some(x=>x.title==='Zero')).toBe(false);expect(result.releases.find(x=>x.title==='Unknown seeds')?.selectable).toBe(true);expect(result.releases.find(x=>x.title==='Usenet')?.viability?.reason).not.toBe('zero-seeders');expect(result.releases.find(x=>x.title==='Stale')?.viability?.reason).toBe('stale');});
  it('allows an explicit per-request availability override without changing the relevance classification',async()=>{const f=fixture([release({guid:'zero-override',title:'Zero seeders',seeders:0})]);const result=await f.service.search({...request,budgets:{hideZeroSeeders:false}});expect(result.releases[0]).toMatchObject({title:'Zero seeders',relevance:{classification:'match'},viability:{reason:'zero-seeders'}});expect(result.diagnostics?.ledger.filtered['availability-zero-seeders']).toBeUndefined();});
  it('retains bounded zero-seeder metadata through hide/include/hide continuations but never stores unsafe references',async()=>{
    const f=fixture([release({guid:'zero-transition',title:'Zero transition',seeders:0}),release({guid:'https://private.invalid/unsafe',title:'Unsafe reference'})]);f.settings.generalSearch={maxQueries:1,maxCandidates:10,maxAiCalls:10,batchSize:10,displayLimit:10,hideZeroSeeders:true};f.service=f.rebuild();
    const hidden=await f.service.search({...request,budgets:{queryCount:1,aiCalls:10}});expect(hidden.releases.some(x=>x.title==='Zero transition')).toBe(false);
    const firstPayload=f.state.getGeneralSearchSnapshot(hidden.searchId!)!.payload as {candidateLedger:Array<{public:{title:string};availabilityFilter?:string;sourceQuery?:string}>};
    expect(firstPayload.candidateLedger.some(x=>x.public.title==='Unsafe reference')).toBe(false);expect(firstPayload.candidateLedger.find(x=>x.public.title==='Zero transition')).toMatchObject({availabilityFilter:'zero-seeders',sourceQuery:'film term'});
    const next=(previous:typeof hidden,hideZeroSeeders:boolean)=>f.service.search({...request,action:'find-more',previousSearchId:previous.searchId!,confirmationToken:previous.confirmationToken!,budgets:{queryCount:1,aiCalls:10,hideZeroSeeders}});
    const included=await next(hidden,false);expect(included.releases.some(x=>x.title==='Zero transition')).toBe(true);
    const hiddenAgain=await next(included,true);expect(hiddenAgain.releases.some(x=>x.title==='Zero transition')).toBe(false);
    const shownAgain=await next(hiddenAgain,false);expect(shownAgain.releases.some(x=>x.title==='Zero transition')).toBe(true);
  });
  it('invalidates a refreshed candidate assessment before a later batch is skipped',async()=>{
    const f=fixture([release({guid:'independent-valid',title:'Independent verified'}),release({guid:'metadata-refresh',title:'Old metadata',seeders:0})]);f.settings.generalSearch={maxQueries:1,maxCandidates:10,maxAiCalls:10,batchSize:10,displayLimit:10,hideZeroSeeders:false};f.service=f.rebuild();
    const first=await f.service.search({...request,budgets:{queryCount:1,aiCalls:10,batchSize:10,hideZeroSeeders:false}});
    const hidden=await f.service.search({...request,action:'find-more',previousSearchId:first.searchId!,confirmationToken:first.confirmationToken!,budgets:{queryCount:1,aiCalls:10,batchSize:10,hideZeroSeeders:true}});
    f.prowlarr.search=vi.fn(async()=>[release({guid:'new-independent',title:'New result'}),release({guid:'metadata-refresh',title:'Updated metadata',seeders:4})]) as never;
    f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning'))return searchPlan('refresh metadata');const d=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};return {items:d.actualResults.map(x=>({releaseId:x.releaseId,classification:'match'}))};}) as never;
    const turns=[{role:'user',content:'find a film'},{role:'assistant',content:'Refine?'},{role:'user',content:'include more'}] as const;
    const refreshed=await f.service.search({...request,turns,action:'follow-up',previousSearchId:hidden.searchId!,confirmationToken:hidden.confirmationToken!,budgets:{queryCount:1,aiCalls:2,batchSize:1,hideZeroSeeders:false}});
    const snapshot=f.state.getGeneralSearchSnapshot(refreshed.searchId!)!.payload as {releases:Array<{public:{releaseId:string;title:string}}> ;candidateLedger:Array<{public:{releaseId:string;title:string;assessment:{status:string}}}>};
    const refreshedId=first.releases.find(x=>x.title==='Old metadata')?.releaseId;
    expect(refreshed.diagnostics?.ledger).toMatchObject({added:1,reactivated:1});expect(refreshed.releases.some(x=>x.title==='Independent verified'&&x.selectable)).toBe(true);
    expect(refreshed.releases.some(x=>x.releaseId===refreshedId)).toBe(false);expect(snapshot.releases.some(x=>x.public.releaseId===refreshedId)).toBe(false);
    expect(snapshot.candidateLedger.find(x=>x.public.releaseId===refreshedId)).toMatchObject({public:{title:'Updated metadata',assessment:{status:'unassessed'}}});
  });
  it('stops after two low-yield rounds instead of exhausting the query ceiling',async()=>{const f=fixture();f.settings.generalSearch={maxQueries:5,maxCandidates:100,maxAiCalls:12,batchSize:20,displayLimit:20,hideZeroSeeders:true};f.service=f.rebuild();f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning'))return searchPlan('one','two','three','four','five');const data=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};return {items:data.actualResults.map(x=>({releaseId:x.releaseId,classification:'match'}))};}) as never;f.prowlarr.search=vi.fn(async({query}:{query:string})=>[release({guid:`${query}-one`,title:query}),...Array.from({length:19},(_,i)=>release({guid:`https://private.invalid/${query}-${i}`,title:`Other ${i}`}))]) as never;const result=await f.service.search({...request,budgets:{queryCount:5,candidateCap:100,batchSize:20,aiCalls:12}});expect(f.prowlarr.search).toHaveBeenCalledTimes(2);expect(result.diagnostics).toMatchObject({stopReason:'low-yield',complete:true});});
  it('returns and snapshots admitted candidates beyond displayLimit',async()=>{const f=fixture(Array.from({length:45},(_,i)=>release({guid:`guid-${i}`,title:`Film ${i}`})));f.settings.generalSearch={maxQueries:1,maxCandidates:100,maxAiCalls:10,batchSize:50,displayLimit:40,hideZeroSeeders:true};f.service=f.rebuild();const result=await f.service.search({...request,budgets:{displayLimit:3,candidateCap:100,batchSize:50,aiCalls:10,queryCount:1}});expect(result.releases).toHaveLength(45);const snapshot=f.state.getGeneralSearchSnapshot(result.searchId!);expect((snapshot?.payload as {releases:unknown[]}).releases).toHaveLength(45);});
  it('find-more uses action and prior sanitized results, creates a new selectable cumulative snapshot and preserves prior expiry',async()=>{
    const f=fixture([release({guid:'first-guid',title:'First title'})]);
    f.settings.generalSearch={maxQueries:1,maxCandidates:20,maxAiCalls:5,batchSize:20,displayLimit:1,hideZeroSeeders:true};f.service=f.rebuild();
    let planning=0;
    f.llm.json=vi.fn(async(args:{label:string;user:string})=>{
      if(args.label.includes('planning')) { planning++; const input=JSON.parse(args.user) as {action:string;previousResults:Array<{title:string}>};
        if(input.action==='find-more') { expect(input.previousResults[0]?.title).toBe('First title'); return searchPlan('fresh term'); }
        return searchPlan('first term'); }
      const data=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};return {items:data.actualResults.map(x=>({releaseId:x.releaseId,classification:'match'}))};
    }) as never;
    const first=await f.service.search({...request,budgets:{queryCount:1,aiCalls:4}});
    const firstExpiry=first.releases[0]!.expiresAt;
    f.prowlarr.search=vi.fn(async({query}:{query:string})=>[release({guid:query==='fresh term'?'second-guid':'first-guid',title:query==='fresh term'?'Second title':'First title'})]) as never;
    const next=await f.service.search({...request,action:'find-more',previousSearchId:first.searchId!,confirmationToken:first.confirmationToken!,budgets:{queryCount:1,aiCalls:4}});
    expect(planning).toBe(2);expect(next.searchId).not.toBe(first.searchId);expect(next.releases.map(x=>x.releaseId)).toContain(first.releases[0]!.releaseId);expect(next.releases.find(x=>x.title==='First title')?.expiresAt).toBe(firstExpiry);expect(next.releases.find(x=>x.title==='Second title')?.selectable).toBe(true);
    const saved=f.state.getGeneralSearchSnapshot(next.searchId!);expect((saved?.payload as {releases:unknown[]}).releases).toHaveLength(2);expect(next.queries).toContain('fresh term');
  });
  it('discovers additional identities when find-more starts with twenty admitted candidates',async()=>{
    const f=fixture(Array.from({length:20},(_,i)=>release({guid:`prior-${i}`,title:`Prior ${i}`})));f.settings.generalSearch={maxQueries:1,maxCandidates:50,maxAiCalls:5,batchSize:20,displayLimit:40,hideZeroSeeders:true};f.service=f.rebuild();
    const first=await f.service.search({...request,budgets:{queryCount:1,candidateCap:50,aiCalls:5}});
    f.prowlarr.search=vi.fn(async()=>[release({guid:'new-find-more',title:'Additional title'})]) as never;
    f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning'))return searchPlan('additional branch');const data=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};return {items:data.actualResults.map(x=>({releaseId:x.releaseId,classification:'match'}))};}) as never;
    const next=await f.service.search({...request,action:'find-more',previousSearchId:first.searchId!,confirmationToken:first.confirmationToken!,budgets:{queryCount:1,candidateCap:50,aiCalls:5}});
    expect(next.releases).toHaveLength(21);expect(next.releases.some(x=>x.title==='Additional title')).toBe(true);
  });
  it('migrates a Phase 1-shaped snapshot and only returns selectable IDs persisted in its authoritative release list',async()=>{
    const f=fixture([release({guid:'phase1-guid',title:'Phase 1 candidate'})]);f.settings.generalSearch={maxQueries:1,maxCandidates:20,maxAiCalls:8,batchSize:20,displayLimit:20,hideZeroSeeders:true};f.service=f.rebuild();
    const first=await f.service.search({...request,budgets:{queryCount:1,aiCalls:8}}),old=f.state.getGeneralSearchSnapshot(first.searchId!)!;
    const payload=old.payload as {releases:Array<{public:Record<string,unknown>}>};for(const item of payload.releases){delete item.public.assessment;delete item.public.relevance;}
    const legacyPayload={releases:payload.releases,queries:['film term'],originalDigest:(old.payload as {originalDigest:string}).originalDigest,runtimeFingerprint:(old.payload as {runtimeFingerprint:string}).runtimeFingerprint,destinationResolved:true};
    (f.state as unknown as {db:{prepare:(sql:string)=>{run:(json:string,id:string)=>void}}}).db.prepare('UPDATE general_search_snapshots SET payload_json=? WHERE id=?').run(JSON.stringify(legacyPayload),first.searchId!);
    const continued=await f.service.search({...request,action:'find-more',previousSearchId:first.searchId!,confirmationToken:first.confirmationToken!,budgets:{queryCount:1,aiCalls:8}});
    const persisted=f.state.getGeneralSearchSnapshot(continued.searchId!)!.payload as {releases:Array<{public:{releaseId:string;selectable:boolean}}>};
    const selectable=continued.releases.filter(x=>x.selectable).map(x=>x.releaseId);expect(selectable.length).toBeGreaterThan(0);expect(selectable).toEqual(persisted.releases.filter(x=>x.public.selectable).map(x=>x.public.releaseId));
    expect(continued.releases.find(x=>x.title==='Phase 1 candidate')?.expiresAt).toBe(first.releases[0]?.expiresAt);
    f.llm.json=vi.fn(async()=>(clarifyPlan('Which format?'))) as never;
    const clarification=await f.service.search({...request,action:'follow-up',previousSearchId:first.searchId!,confirmationToken:first.confirmationToken!,budgets:{queryCount:1,aiCalls:8}});
    const clarifiedSnapshot=f.state.getGeneralSearchSnapshot(clarification.searchId!)!.payload as {releases:Array<unknown>;candidateLedger:Array<{public:{releaseId:string;selectable:boolean;expiresAt:string}}>};
    expect(clarification.status).toBe('clarification-needed');expect(clarification.releases).toMatchObject([{releaseId:first.releases[0]?.releaseId,selectable:false,expiresAt:first.releases[0]?.expiresAt}]);
    expect(clarifiedSnapshot.releases).toEqual([]);expect(clarifiedSnapshot.candidateLedger[0]?.public).toMatchObject({releaseId:clarification.releases[0]?.releaseId,selectable:false,expiresAt:first.releases[0]?.expiresAt});
    f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning'))return searchPlan('film term');const d=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};return {items:d.actualResults.map(x=>({releaseId:x.releaseId,classification:'match'}))};}) as never;
    const answered=await f.service.search({...request,action:'follow-up',previousSearchId:clarification.searchId!,confirmationToken:clarification.confirmationToken!,budgets:{queryCount:1,aiCalls:8}});
    const answeredSnapshot=f.state.getGeneralSearchSnapshot(answered.searchId!)!.payload as {releases:Array<{public:{releaseId:string;selectable:boolean}}>};
    expect(answered.releases).toMatchObject([{releaseId:clarification.releases[0]?.releaseId,selectable:true,expiresAt:first.releases[0]?.expiresAt}]);expect(answeredSnapshot.releases.map(x=>x.public.releaseId)).toContain(answered.releases[0]?.releaseId);expect(answeredSnapshot.releases.find(x=>x.public.releaseId===answered.releases[0]?.releaseId)?.public.selectable).toBe(true);
  });
  it('reassesses prior candidates against changed exclusions and allows a later override without renewing expiry',async()=>{const f=fixture([release({guid:'constraint-guid',title:'Family adventure'})]);f.settings.generalSearch={maxQueries:1,maxCandidates:20,maxAiCalls:10,batchSize:20,displayLimit:20,hideZeroSeeders:true};f.service=f.rebuild();let planners=0,curations=0;f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning')){planners++;return {...searchPlan('film term'),searchSpace:{...searchPlan('x').searchSpace,focus:'mixed',identityAnchors:[],medium:{value:'film',provenance:'explicit'},positives:[],negatives:planners===2?[{text:'exclude family films',strength:'hard'}]:[],expansionScope:'identity-preserving'}};}curations++;const input=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>;constraints:{negatives:Array<{text:string}>}};return {items:input.actualResults.map(x=>({releaseId:x.releaseId,classification:curations===2?'clearly-unrelated':'match'}))};}) as never;const first=await f.service.search({...request,budgets:{queryCount:1,aiCalls:10}});const id=first.releases[0]!.releaseId,expiry=first.releases[0]!.expiresAt;const turns=[{role:'user',content:'find a film'},{role:'assistant',content:'Any exclusions?'},{role:'user',content:'exclude family films'}] as const;const excluded=await f.service.search({...request,turns,action:'follow-up',previousSearchId:first.searchId!,confirmationToken:first.confirmationToken!,budgets:{queryCount:1,aiCalls:10}});expect(excluded.releases).toHaveLength(0);const payload=f.state.getGeneralSearchSnapshot(excluded.searchId!)!.payload as {releases:unknown[];candidateLedger:Array<{public:{assessment:{status:string}}}>};expect(payload.releases).toEqual([]);expect(payload.candidateLedger[0]?.public.assessment.status).toBe('rejected');const overrideTurns=[...turns.slice(0,2),{role:'user' as const,content:'include family films after all'}] as const;f.prowlarr.search=vi.fn(async()=>[release({guid:'constraint-guid',title:'Family adventure'})]) as never;const override=await f.service.search({...request,turns:overrideTurns,action:'follow-up',previousSearchId:excluded.searchId!,confirmationToken:excluded.confirmationToken!,budgets:{queryCount:1,aiCalls:10}});expect(override.releases.map(x=>x.releaseId)).toEqual([id]);expect(override.releases[0]?.expiresAt).toBe(expiry);expect(override.releases[0]?.selectable).toBe(true);expect(f.prowlarr.search).toHaveBeenCalledTimes(1);});
  it('keeps budget-skipped prior candidates unassessed and reevaluates them when budget permits',async()=>{const f=fixture([release({guid:'unassessed-guid',title:'Unassessed candidate'})]);f.settings.generalSearch={maxQueries:1,maxCandidates:20,maxAiCalls:8,batchSize:20,displayLimit:20,hideZeroSeeders:true};f.service=f.rebuild();let planning=0;f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning')){planning++;return {...searchPlan('film term'),searchSpace:{...searchPlan('film term').searchSpace,positives:planning===1?[]:[{text:'documentary',strength:'hard'}]}};}const d=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};return {items:d.actualResults.map(x=>({releaseId:x.releaseId,classification:'match'}))};}) as never;const first=await f.service.search({...request,budgets:{queryCount:1,aiCalls:8}});const turns=[{role:'user',content:'find a film'},{role:'assistant',content:'Refine?'},{role:'user',content:'prefer documentaries'}] as const;const skipped=await f.service.search({...request,turns,action:'follow-up',previousSearchId:first.searchId!,confirmationToken:first.confirmationToken!,budgets:{queryCount:1,aiCalls:1}});expect(skipped.releases).toEqual([]);const skippedPayload=f.state.getGeneralSearchSnapshot(skipped.searchId!)!.payload as {releases:unknown[];candidateLedger:Array<{public:{assessment:{status:string}}}>};expect(skippedPayload.releases).toEqual([]);expect(skippedPayload.candidateLedger[0]?.public.assessment.status).toBe('unassessed');const recovered=await f.service.search({...request,turns,action:'follow-up',previousSearchId:skipped.searchId!,confirmationToken:skipped.confirmationToken!,budgets:{queryCount:1,aiCalls:8}});expect(recovered.releases).toHaveLength(1);expect(recovered.releases[0]?.selectable).toBe(true);});
  it('reassesses old candidates in bounded batches and counts every budget-skipped item as pending',async()=>{
    const f=fixture(Array.from({length:5},(_,i)=>release({guid:`reassess-${i}`,title:`Reassess ${i}`})));f.settings.generalSearch={maxQueries:1,maxCandidates:20,maxAiCalls:12,batchSize:5,displayLimit:20,hideZeroSeeders:true};f.service=f.rebuild();
    const first=await f.service.search({...request,budgets:{queryCount:1,batchSize:5,aiCalls:8}});
    const calls: number[]=[];f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning'))return {...searchPlan('film term'),searchSpace:{...searchPlan('x').searchSpace,focus:'mixed',identityAnchors:[],medium:{value:'film',provenance:'explicit'},positives:[{text:'documentary',strength:'hard'}],negatives:[],expansionScope:'identity-preserving'}};const d=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};calls.push(d.actualResults.length);return {items:d.actualResults.map(x=>({releaseId:x.releaseId,classification:'match'}))};}) as never;
    const turns=[{role:'user',content:'find a film'},{role:'assistant',content:'Refine?'},{role:'user',content:'documentaries only'}] as const;
    const next=await f.service.search({...request,turns,action:'follow-up',previousSearchId:first.searchId!,confirmationToken:first.confirmationToken!,budgets:{queryCount:1,batchSize:2,aiCalls:3}});
    expect(calls).toEqual([2,2]);expect(next.releases).toHaveLength(4);expect(next.diagnostics?.ledger.reassessed).toBe(4);expect(next.diagnostics?.ledger.assessed).toMatchObject({match:4,unassessed:1});
    const saved=f.state.getGeneralSearchSnapshot(next.searchId!)!.payload as {releases:Array<unknown>;candidateLedger:Array<{public:{assessment:{status:string}}}>};expect(saved.releases).toHaveLength(4);expect(saved.candidateLedger.filter(x=>x.public.assessment.status==='unassessed')).toHaveLength(1);
  });
  it('refreshes a rejected identity at candidateCap one without treating it as a new admission',async()=>{
    const f=fixture([release({guid:'cap-one-rejected',title:'Reversible match'})]);f.settings.generalSearch={maxQueries:1,maxCandidates:1,maxAiCalls:10,batchSize:1,displayLimit:10,hideZeroSeeders:true};f.service=f.rebuild();let planning=0,curation=0;
    f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning')){planning++;const space={...searchPlan('film term').searchSpace,focus:'mixed',identityAnchors:[],medium:{value:'film',provenance:'explicit'},positives:[],negatives:[],expansionScope:'identity-preserving'};return {...searchPlan('film term'),searchSpace:planning===1?space:{...space,positives:[{text:'include family adventure',strength:'hard'}]}};}const d=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};curation++;return {items:d.actualResults.map(x=>({releaseId:x.releaseId,classification:curation===1?'clearly-unrelated':'match'}))};}) as never;
    const first=await f.service.search({...request,budgets:{queryCount:1,candidateCap:1,batchSize:1,aiCalls:10}});const firstPool=f.state.getGeneralSearchSnapshot(first.searchId!)!.payload as {candidateLedger:Array<{public:{releaseId:string;expiresAt:string}}>};const previous=firstPool.candidateLedger[0]!.public;const turns=[{role:'user',content:'find a film'},{role:'assistant',content:'What kind?'},{role:'user',content:'include family adventure'}] as const;
    const next=await f.service.search({...request,turns,action:'follow-up',previousSearchId:first.searchId!,confirmationToken:first.confirmationToken!,budgets:{queryCount:1,candidateCap:1,batchSize:1,aiCalls:10}});
    expect(next.releases).toHaveLength(1);expect(next.releases[0]?.releaseId).toBe(previous.releaseId);expect(next.releases[0]?.expiresAt).toBe(previous.expiresAt);expect(next.diagnostics?.ledger).toMatchObject({added:0,reactivated:1});
  });
  it('uses actual results for iterative refinement and never emits an uncurated candidate',async()=>{
    const f=fixture([release({guid:'iter-1',title:'First batch'})]);f.settings.generalSearch={maxQueries:2,maxCandidates:20,maxAiCalls:8,batchSize:20,displayLimit:20,hideZeroSeeders:true};f.service=f.rebuild();
    let calls=0;f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning')){const input=JSON.parse(args.user) as {inspiration?:{lastQuery?:string;results?:Array<{title:string}>};ledger?:{current?:{raw:number;new:number;assessed:{match:number}}}};if(input.inspiration?.lastQuery){expect(input.inspiration.results?.[0]?.title).toBe('First batch');expect(input.ledger?.current).toMatchObject({raw:1,new:1,assessed:{match:1}});return searchPlan('second term');}return searchPlan('first term');}const data=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};calls++;return {items:data.actualResults.map(x=>({releaseId:x.releaseId,classification:'match'}))};}) as never;
    f.prowlarr.search=vi.fn(async({query}:{query:string})=>[release({guid:query,title:query==='first term'?'First batch':'Second batch'})]) as never;
    const emitted: string[]=[];const result=await f.service.search({...request,budgets:{queryCount:2,aiCalls:8}},e=>{if(e.type==='results')emitted.push(...e.releases.map(x=>x.title));});
    expect(f.prowlarr.search).toHaveBeenCalledTimes(2);expect(result.queries).toEqual(['first term','second term']);expect(calls).toBe(2);expect(emitted).toContain('First batch');expect(emitted).toContain('Second batch');
  });
  it('emits verified partial candidates as nonselectable on a later safe refusal and creates no snapshot',async()=>{const f=fixture([release({guid:'partial-one',title:'Verified partial'})]);f.settings.generalSearch={maxQueries:2,maxCandidates:20,maxAiCalls:10,batchSize:20,displayLimit:20,hideZeroSeeders:true};f.service=f.rebuild();let planning=0;f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning')){if(++planning===1)return searchPlan('first');throw Object.assign(new Error('LLM completion included a refusal private-secret'),{code:'provider-refusal'});}const d=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};return {items:d.actualResults.map(x=>({releaseId:x.releaseId,classification:'match'}))};}) as never;f.prowlarr.search=vi.fn(async()=>[release({guid:'partial-one',title:'Verified partial'})]) as never;const save=vi.spyOn(f.state,'saveGeneralSearchSnapshot'),events:unknown[]=[];await expect(f.service.search({...request,budgets:{queryCount:2,aiCalls:10}},e=>events.push(e))).rejects.toMatchObject({code:'provider-refusal'});expect(save).not.toHaveBeenCalled();const error=events.at(-1) as {partialReleases?:Array<{title:string;selectable:boolean}>;diagnostics?:unknown};expect(error).toMatchObject({type:'error',code:'provider-refusal',partialReleases:[{title:'Verified partial',selectable:false}],diagnostics:{complete:false,stopReason:'provider-refusal'}});expect(JSON.stringify(events)).not.toContain('private-secret');});
  it('reports a retrieved identity and its added count even when its first curation fails',async()=>{
    const f=fixture([release({guid:'retrieved-before-curation',title:'Pending curation'})]);f.llm.json=vi.fn(async(args:{label:string})=>args.label.includes('planning')?searchPlan('one branch'):Promise.reject(Object.assign(new Error('invalid-llm-output'),{code:'invalid-llm-output'}))) as never;
    const events:unknown[]=[];await expect(f.service.search({...request,budgets:{queryCount:1,aiCalls:3}},e=>events.push(e))).rejects.toMatchObject({code:'invalid-llm-output'});
    expect(events.at(-1)).toMatchObject({type:'error',diagnostics:{complete:false,ledger:{raw:1,added:1,outcomes:[{query:'one branch',outcome:'success',raw:1,added:1}],assessed:{unassessed:1}}}});
  });
  it('does not search or persist when the planner exhausts the AI budget',async()=>{const f=fixture();const result=await f.service.search({...request,budgets:{aiCalls:1,queryCount:4}});expect(f.prowlarr.search).not.toHaveBeenCalled();expect(result.releases).toEqual([]);expect(f.state.getGeneralSearchSnapshot(result.searchId!)?.payload).toBeTruthy();});
  it('charges correction and transport attempts before each provider send',async()=>{
    for(const retry of ['correction','transport']) {
      const f=fixture();f.llm.json=vi.fn(async(args:{onAttempt?:(a:{logicalAttempt:number;transportAttempt:number})=>void})=>{
        args.onAttempt?.({logicalAttempt:0,transportAttempt:0});
        args.onAttempt?.(retry==='correction'?{logicalAttempt:1,transportAttempt:0}:{logicalAttempt:0,transportAttempt:1});
        return searchPlan('should-not-run');
      }) as never;
      await expect(f.service.search({...request,budgets:{aiCalls:1,queryCount:1}})).rejects.toMatchObject({code:'ai-budget-exhausted'});
      expect(f.prowlarr.search).not.toHaveBeenCalled();
    }
  });
  it('counts planner and every curation batch against AI budget and candidate cap',async()=>{
    const f=fixture(Array.from({length:8},(_,i)=>release({guid:`batch-${i}`,title:`Batch ${i}`})));
    const result=await f.service.search({...request,budgets:{queryCount:1,candidateCap:5,batchSize:2,aiCalls:4,displayLimit:1}});
    expect(f.llm.json).toHaveBeenCalledTimes(4); // planner + three bounded curation batches
    expect(result.releases).toHaveLength(5);expect((f.state.getGeneralSearchSnapshot(result.searchId!)?.payload as {releases:unknown[]}).releases).toHaveLength(5);
    const capped=fixture(Array.from({length:8},(_,i)=>release({guid:`cap-${i}`})));
    const capResult=await capped.service.search({...request,budgets:{queryCount:1,candidateCap:3,batchSize:2,aiCalls:3}});
    expect(capResult.releases).toHaveLength(3);
  });
  it('fails closed on unknown, duplicate, or missing curation classifications',async()=>{
    for(const mode of ['unknown','duplicate','missing']) {
      const f=fixture();
      f.llm.json=vi.fn(async(args:{label:string;user:string})=>{
        if(args.label.includes('planning')) return searchPlan('term');
        const data=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};
        const id=data.actualResults[0]!.releaseId;
        const items=mode==='unknown'?[{releaseId:'invented',classification:'match'}]:mode==='duplicate'?[{releaseId:id,classification:'match'},{releaseId:id,classification:'possible-match'}]:[];
        return {items};
      }) as never;
      await expect(f.service.search({...request,budgets:{queryCount:1,aiCalls:2}})).rejects.toMatchObject({code:'invalid-curation'});
    }
  });
  it('remembers rejected release identities across new snapshots without persisting raw metadata',async()=>{
    const f=fixture([release({guid:'repeat-guid',title:'Unrelated candidate'})]);f.settings.generalSearch={maxQueries:1,maxCandidates:20,maxAiCalls:5,batchSize:20,displayLimit:20,hideZeroSeeders:true};f.service=f.rebuild();
    let plans=0;f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning')){plans++;return searchPlan(plans===1?'first term':'second term');}const d=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};return {items:d.actualResults.map(x=>({releaseId:x.releaseId,classification:'clearly-unrelated'}))};}) as never;
    const progress:number[]=[];const first=await f.service.search({...request,budgets:{queryCount:1,aiCalls:3}},e=>{if(e.type==='curation')progress.push(e.processed);});expect(first.releases).toHaveLength(0);expect(progress).toContain(0);expect(progress).toContain(1);
    const second=await f.service.search({...request,action:'find-more',previousSearchId:first.searchId!,confirmationToken:first.confirmationToken!,budgets:{queryCount:1,aiCalls:3}});
    expect(f.prowlarr.search).toHaveBeenCalledTimes(2);expect(second.releases).toHaveLength(0);expect(JSON.stringify(f.state.getGeneralSearchSnapshot(second.searchId!)?.payload)).not.toContain('repeat-guid');
  });
  it('enforces snapshot continuation limits and immutable original-query identity',async()=>{
    const f=fixture();f.settings.generalSearch={maxQueries:1,maxCandidates:20,maxAiCalls:12,batchSize:20,displayLimit:20,hideZeroSeeders:true};f.service=f.rebuild();let term=0;
    f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning'))return searchPlan(`continued-${++term}`);const d=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};return {items:d.actualResults.map(x=>({releaseId:x.releaseId,classification:'match'}))};}) as never;
    f.prowlarr.search=vi.fn(async({query}:{query:string})=>[release({guid:query,title:query})]) as never;
    let response=await f.service.search({...request,budgets:{queryCount:1,aiCalls:12}});
    for(let i=0;i<5;i++)response=await f.service.search({...request,action:'find-more',previousSearchId:response.searchId!,confirmationToken:response.confirmationToken!,budgets:{queryCount:1,aiCalls:12}});
    await expect(f.service.search({...request,action:'find-more',previousSearchId:response.searchId!,confirmationToken:response.confirmationToken!,budgets:{queryCount:1,aiCalls:12}})).rejects.toMatchObject({code:'follow-up-limit'});
    await expect(f.service.search({...request,originalQuery:'different',turns:[{role:'user',content:'different'}],action:'find-more',previousSearchId:response.searchId!,confirmationToken:response.confirmationToken!,budgets:{queryCount:1,aiCalls:12}})).rejects.toMatchObject({code:'invalid-request'});
  });
  it('rejects unknown budget keys and incompatible or unknown protocols before curation',async()=>{
    const f=fixture([release({guid:'news',protocol:'usenet'}),release({guid:'unknown',protocol:'unknown'})]);
    await expect(f.service.search({...request,budgets:{queryCount:1,unexpected:2}})).rejects.toMatchObject({code:'invalid-budget'});
    const result=await f.service.search({...request,budgets:{queryCount:1,aiCalls:3}});
    expect(result.releases).toHaveLength(0);expect(f.llm.json).toHaveBeenCalledTimes(1);
  });
  it('keeps known safe releases visible but nonselectable for ambiguous or incomplete routing',async()=>{
    const routingCases=[[],[{id:1,name:'General',enable:true,protocol:'torrent',supportsCategories:true,categories:[],routingDigest:''}],[1,2].map(id=>({id,name:'General',enable:true,protocol:'torrent',supportsCategories:true,categories:[],routingDigest:'a'.repeat(64)}))];
    for(const clients of routingCases){const f=fixture();f.prowlarr.getDownloadClients=vi.fn(async()=>clients) as never;const result=await f.service.search({...request,budgets:{queryCount:1,aiCalls:2}});expect(result.releases).toHaveLength(1);expect(result.releases[0]?.selectable).toBe(false);expect(result.blockedReason).toBe('destination-unavailable');}
  });
  it('carries clarification turns into planning and curation and enforces five follow-ups',async()=>{
    const f=fixture();f.settings.generalSearch={maxQueries:1,maxCandidates:20,maxAiCalls:4,batchSize:20,displayLimit:20,hideZeroSeeders:true};f.service=f.rebuild();
    const evidence:string[]=[];
    f.llm.json=vi.fn(async(args:{label:string;user:string})=>{evidence.push(args.user);if(args.label.includes('planning'))return searchPlan('answer-specific term');const data=JSON.parse(args.user) as {conversation:Array<{content:string}>;actualResults:Array<{releaseId:string}>};expect(data.conversation.some(x=>x.content.includes('prefer documentaries'))).toBe(true);return {items:data.actualResults.map(x=>({releaseId:x.releaseId,classification:'possible-match'}))};}) as never;
    const turns=[{role:'user',content:'find a film'},{role:'assistant',content:'Which style?'},{role:'user',content:'prefer documentaries'}] as const;
    await f.service.search({...request,turns,action:'follow-up',budgets:{queryCount:1,aiCalls:4}});
    expect(evidence).toHaveLength(2);expect(evidence[0]).toContain('prefer documentaries');
    const over={...request,turns:Array.from({length:13},(_,i)=>({role:(i%2?'assistant':'user') as 'assistant'|'user',content:i===0?'find a film':'clarification '.repeat(1)}))};
    await expect(f.service.search(over)).rejects.toMatchObject({code:'invalid-request'});
  });
  it('clarification responses retain authenticated result metadata without storing transcript turns',async()=>{
    const f=fixture();const first=await f.service.search({...request,budgets:{queryCount:1,aiCalls:3}}),expiry=first.releases[0]!.expiresAt;
    f.llm.json=vi.fn(async()=>(clarifyPlan('Which decade?'))) as never;
    const clarification=await f.service.search({...request,action:'follow-up',previousSearchId:first.searchId!,confirmationToken:first.confirmationToken!});
    expect(clarification.status).toBe('clarification-needed');expect(clarification.releases[0]?.releaseId).toBe(first.releases[0]?.releaseId);expect(clarification.releases[0]?.expiresAt).toBe(expiry);expect(clarification.destination?.name).toBe('General');
    const payload=f.state.getGeneralSearchSnapshot(clarification.searchId!)?.payload as Record<string,unknown>;expect(payload.originalDigest).toBeDefined();expect(payload.turns).toBeUndefined();
  });
  it('does not recertify previously admitted releases when the revised continuation asks for clarification',async()=>{
    const f=fixture([release({guid:'clarify-tightened',title:'Previously matched'})]);const first=await f.service.search({...request,budgets:{queryCount:1,aiCalls:4}});
    f.llm.json=vi.fn(async()=>(({...clarifyPlan('Which specific medium?'),searchSpace:{...clarifyPlan('Which specific medium?').searchSpace,positives:[{text:'documentary only',strength:'hard'}]}}))) as never;
    const turns=[{role:'user',content:'find a film'},{role:'assistant',content:'Which type?'},{role:'user',content:'documentary only'}] as const;
    const clarification=await f.service.search({...request,turns,action:'follow-up',previousSearchId:first.searchId!,confirmationToken:first.confirmationToken!,budgets:{queryCount:1,aiCalls:4}});
    expect(clarification.status).toBe('clarification-needed');expect(clarification.releases).toMatchObject([{releaseId:first.releases[0]!.releaseId,selectable:false}]);
    const payload=f.state.getGeneralSearchSnapshot(clarification.searchId!)!.payload as {releases:Array<unknown>;candidateLedger:Array<{public:{releaseId:string;assessment:{status:string}}}>};
    expect(payload.releases).toEqual([]);expect(payload.candidateLedger[0]).toMatchObject({public:{releaseId:first.releases[0]!.releaseId,assessment:{status:'unassessed'}}});
  });
  it('checks cancellation and AI/source drift after upstream awaits before further work or saving',async()=>{
    const f=fixture();let finish!:()=>void, entered!:()=>void;const gate=new Promise<void>(resolve=>{finish=resolve;}),started=new Promise<void>(resolve=>{entered=resolve;});
    f.prowlarr.search=vi.fn(async()=>{entered();await gate;return [release()];}) as never;
    const pending=f.service.search({...request,budgets:{queryCount:1,aiCalls:4}});await started;f.settings.ai.apiKey='rotated-key';finish();await expect(pending).rejects.toMatchObject({code:'settings-changed'});expect(f.llm.json).toHaveBeenCalledTimes(1);
  });
  it('keeps discovery visible but nonselectable without a destination and sanitizes destination names',async()=>{
    const f=fixture();f.prowlarr.getDownloadClients=vi.fn(async()=>[]) as never;
    const result=await f.service.search({...request,budgets:{queryCount:1,aiCalls:2}});
    expect(result.releases).toHaveLength(1);expect(result.releases[0]?.selectable).toBe(false);expect(result.blockedReason).toBe('destination-unavailable');
    const privateDestination=fixture();privateDestination.settings.integrations.prowlarr.generalClient='private-token=destination-secret';privateDestination.service=privateDestination.rebuild();privateDestination.prowlarr.getDownloadClients=vi.fn(async()=>[{id:1,name:'private-token=destination-secret',enable:true,protocol:'torrent',supportsCategories:true,categories:[],routingDigest:'a'.repeat(64)}]) as never;
    await expect(privateDestination.service.search({...request,budgets:{queryCount:1,aiCalls:2}})).rejects.toMatchObject({code:'destination-unavailable'});
  });
  it('rejects request budgets above configured settings and emits each refined query proposal',async()=>{
    const f=fixture();f.settings.generalSearch={maxQueries:1,maxCandidates:20,maxAiCalls:4,batchSize:20,displayLimit:20,hideZeroSeeders:true};f.service=f.rebuild();
    await expect(f.service.search({...request,budgets:{queryCount:2}})).rejects.toMatchObject({code:'invalid-budget'});
    f.settings.generalSearch.maxQueries=2;f.service=f.rebuild();
    let planning=0;f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning')){planning++;return planning===1?searchPlan('first'):searchPlan('second');}const data=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};return {items:data.actualResults.map(x=>({releaseId:x.releaseId,classification:'match'}))};}) as never;
    f.prowlarr.search=vi.fn(async({query}:{query:string})=>[release({guid:query})]) as never;
    const proposed:string[][]=[];await f.service.search({...request,budgets:{queryCount:2,aiCalls:4}},e=>{if(e.type==='queries')proposed.push(e.queries);});expect(proposed).toEqual([['first'],['second']]);
  });
  it('honors cancellation before any planner or upstream request',async()=>{const f=fixture();const controller=new AbortController();controller.abort();await expect(f.service.search(request,undefined,controller.signal)).rejects.toMatchObject({code:'aborted'});expect(f.llm.json).not.toHaveBeenCalled();expect(f.prowlarr.getDownloadClients).not.toHaveBeenCalled();});
  it('rejects prior snapshots when the destination routing identity changes',async()=>{
    const f=fixture();f.settings.generalSearch={maxQueries:1,maxCandidates:20,maxAiCalls:4,batchSize:20,displayLimit:20,hideZeroSeeders:true};f.service=f.rebuild();
    const first=await f.service.search({...request,budgets:{queryCount:1,aiCalls:4}});
    const llmCalls=f.llm.json.mock.calls.length;f.llm.json=vi.fn(async()=>(clarifyPlan('Which?'))) as never;
    f.prowlarr.getDownloadClients=vi.fn(async()=>[{id:99,name:'General',enable:true,protocol:'torrent',supportsCategories:true,categories:[],routingDigest:'b'.repeat(64)}]) as never;
    await expect(f.service.search({...request,action:'find-more',previousSearchId:first.searchId!,confirmationToken:first.confirmationToken!,budgets:{queryCount:1,aiCalls:4}})).rejects.toMatchObject({code:'destination-changed'});
    expect(f.prowlarr.search).toHaveBeenCalledTimes(1);expect(f.llm.json).not.toHaveBeenCalled();expect(llmCalls).toBeGreaterThan(0);
  });
  it('rechecks runtime identity after planner and curation awaits',async()=>{
    const plannerFixture=fixture();let finishPlan!:()=>void,enteredPlan!:()=>void;const planGate=new Promise<void>(resolve=>{finishPlan=resolve;}),planStarted=new Promise<void>(resolve=>{enteredPlan=resolve;});
    plannerFixture.llm.json=vi.fn(async()=>{enteredPlan();await planGate;return searchPlan('term');}) as never;
    const planning=plannerFixture.service.search(request);await planStarted;plannerFixture.settings.integrations.prowlarr.apiKey='rotated-source';finishPlan();await expect(planning).rejects.toMatchObject({code:'settings-changed'});expect(plannerFixture.prowlarr.search).not.toHaveBeenCalled();expect(plannerFixture.llm.json).toHaveBeenCalledTimes(1);
    const curationFixture=fixture();let finishCuration!:()=>void,enteredCuration!:()=>void;const curationGate=new Promise<void>(resolve=>{finishCuration=resolve;}),curationStarted=new Promise<void>(resolve=>{enteredCuration=resolve;});
    curationFixture.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning'))return searchPlan('term');enteredCuration();await curationGate;const input=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};return {items:input.actualResults.map(x=>({releaseId:x.releaseId,classification:'match'}))};}) as never;
    const curating=curationFixture.service.search({...request,budgets:{queryCount:1,aiCalls:4}});await curationStarted;curationFixture.settings.ai.apiKey='changed-ai-key';finishCuration();await expect(curating).rejects.toMatchObject({code:'settings-changed'});
  });
  it('rejects a previous snapshot after AI identity drift before another paid call',async()=>{
    const f=fixture();const first=await f.service.search({...request,budgets:{queryCount:1,aiCalls:3}});const before=f.llm.json.mock.calls.length;f.settings.ai.model='different-model';
    await expect(f.service.search({...request,action:'find-more',previousSearchId:first.searchId!,confirmationToken:first.confirmationToken!})).rejects.toMatchObject({code:'settings-changed'});expect(f.llm.json).toHaveBeenCalledTimes(before);
  });
  it('enforces the controllable 120-second deadline before curation can complete or snapshots can be saved',async()=>{
    let now=new Date('2026-10-06T12:00:00.000Z');const f=fixture();f.settings.generalSearch={maxQueries:1,maxCandidates:20,maxAiCalls:3,batchSize:20,displayLimit:20,hideZeroSeeders:true};
    f.service=new GeneralSearchConversationService({llm:f.llm as never,prowlarr:f.prowlarr as never,state:f.state,getSettings:()=>f.settings,now:()=>now});
    f.llm.json=vi.fn(async(args:{label:string;user:string})=>{if(args.label.includes('planning'))return searchPlan('term');now=new Date(now.getTime()+16*60_000);const d=JSON.parse(args.user) as {actualResults:Array<{releaseId:string}>};return {items:d.actualResults.map(x=>({releaseId:x.releaseId,classification:'match'}))};}) as never;
    const events:unknown[]=[];const save=vi.spyOn(f.state,'saveGeneralSearchSnapshot');await expect(f.service.search({...request,budgets:{queryCount:1,aiCalls:3}},e=>events.push(e))).rejects.toMatchObject({code:'search-deadline'});expect(save).not.toHaveBeenCalled();expect(JSON.stringify(events)).not.toContain('Example film');expect(events.at(-1)).toMatchObject({type:'error',diagnostics:{complete:false,stopReason:'deadline'}});
  });
  it('checks the deadline around destination resolution and emits only nonselectable prior partials',async()=>{
    let now=new Date('2026-10-06T12:00:00.000Z');const f=fixture([release({guid:'deadline-prior',title:'Prior result'})]);f.settings.generalSearch={maxQueries:1,maxCandidates:20,maxAiCalls:8,batchSize:20,displayLimit:20,hideZeroSeeders:true};
    f.service=new GeneralSearchConversationService({llm:f.llm as never,prowlarr:f.prowlarr as never,state:f.state,getSettings:()=>f.settings,now:()=>now});
    const first=await f.service.search({...request,budgets:{queryCount:1,aiCalls:8}}),prior=f.state.getGeneralSearchSnapshot(first.searchId!)!;
    f.prowlarr.getDownloadClients=vi.fn(async()=>{now=new Date(now.getTime()+121_000);return [{id:1,name:'General',enable:true,protocol:'torrent',supportsCategories:true,categories:[],routingDigest:'a'.repeat(64)}];}) as never;
    const events:unknown[]=[],save=vi.spyOn(f.state,'saveGeneralSearchSnapshot');
    await expect(f.service.search({...request,action:'find-more',previousSearchId:first.searchId!,confirmationToken:first.confirmationToken!,budgets:{queryCount:1,aiCalls:8}},e=>events.push(e))).rejects.toMatchObject({code:'search-deadline'});
    expect(save).not.toHaveBeenCalled();const error=events.at(-1) as {partialReleases?:Array<{releaseId:string;selectable:boolean}>;diagnostics?:unknown};
    expect(error.partialReleases).toEqual([{...first.releases[0],selectable:false}]);expect(error.diagnostics).toMatchObject({complete:false,stopReason:'deadline'});expect(f.state.getGeneralSearchSnapshot(first.searchId!)?.expiresAt).toBe(prior.expiresAt);
  });
  it('does not issue a clarification token or snapshot when clarification crosses the deadline',async()=>{
    let now=new Date('2026-10-06T12:00:00.000Z');const f=fixture([release({guid:'clarify-deadline',title:'Prior candidate'})]);f.settings.generalSearch={maxQueries:1,maxCandidates:20,maxAiCalls:8,batchSize:20,displayLimit:20,hideZeroSeeders:true};
    f.service=new GeneralSearchConversationService({llm:f.llm as never,prowlarr:f.prowlarr as never,state:f.state,getSettings:()=>f.settings,now:()=>now});
    const first=await f.service.search({...request,budgets:{queryCount:1,aiCalls:8}});f.llm.json=vi.fn(async()=>{now=new Date(now.getTime()+121_000);return clarifyPlan('Which medium?');}) as never;
    const events:unknown[]=[],save=vi.spyOn(f.state,'saveGeneralSearchSnapshot');await expect(f.service.search({...request,action:'follow-up',previousSearchId:first.searchId!,confirmationToken:first.confirmationToken!,budgets:{queryCount:1,aiCalls:8}},e=>events.push(e))).rejects.toMatchObject({code:'search-deadline'});
    expect(save).not.toHaveBeenCalled();expect(events.at(-1)).toMatchObject({type:'error',diagnostics:{complete:false,stopReason:'deadline'},partialReleases:[{releaseId:first.releases[0]?.releaseId,selectable:false}]});
  });
  it('rechecks the deadline immediately before final snapshot creation',async()=>{
    let now=new Date('2026-10-06T12:00:00.000Z');const f=fixture([release({guid:'prefinal-deadline',title:'Curated partial'})]);f.settings.generalSearch={maxQueries:1,maxCandidates:20,maxAiCalls:4,batchSize:20,displayLimit:20,hideZeroSeeders:true};
    f.service=new GeneralSearchConversationService({llm:f.llm as never,prowlarr:f.prowlarr as never,state:f.state,getSettings:()=>f.settings,now:()=>now});
    const prune=f.state.pruneGeneralSearchSnapshots.bind(f.state);vi.spyOn(f.state,'pruneGeneralSearchSnapshots').mockImplementation((expiry)=>{prune(expiry);now=new Date(now.getTime()+121_000);});
    const save=vi.spyOn(f.state,'saveGeneralSearchSnapshot'),events:unknown[]=[];await expect(f.service.search({...request,budgets:{queryCount:1,aiCalls:4}},e=>events.push(e))).rejects.toMatchObject({code:'search-deadline'});
    expect(save).not.toHaveBeenCalled();expect(events.at(-1)).toMatchObject({type:'error',diagnostics:{complete:false,stopReason:'deadline'},partialReleases:[{title:'Curated partial',selectable:false}]});
  });
  it('keeps event sequence local across overlapping requests',async()=>{const f=fixture();const gate=new Promise<void>(resolve=>setTimeout(resolve,5));const a:number[]=[],b:number[]=[];const p1=f.service.search(request,e=>a.push(e.sequence));const p2=f.service.search(request,e=>b.push(e.sequence));await Promise.all([p1,p2,gate]);expect(a[0]).toBe(0);expect(b[0]).toBe(0);expect(a).toEqual(a.map((_,i)=>i));expect(b).toEqual(b.map((_,i)=>i));});
  it('rejects overlong conversation turns',async()=>{const f=fixture();await expect(f.service.search({...request,turns:[{role:'user',content:'x'.repeat(501)}]})).rejects.toMatchObject({code:'invalid-request'});});
});
